[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pb_tool"
version = "3.5.3"
description = "A tool to aid in QGIS Python plugin development"
readme = "README.md"
license = { text = "GPL-2.0-or-later" }
authors = [
    { name = "Jonah Sullivan", email = "geosull@pm.me" },
    { name = "Gary Sherman", email = "gsherman@geoapt.com" }
]
keywords = ["QGIS", "PyQGIS"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)",
    "Topic :: Scientific/Engineering :: GIS",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
requires-python = ">=3.9"
dependencies = ["click", "colorama", "configupdater", "defusedxml"]

[project.optional-dependencies]
docs = ["sphinx"]

[project.urls]
Homepage = "https://jonah-sullivan.github.io/plugin_build_tool"
Repository = "https://github.com/jonah-sullivan/plugin_build_tool"
"Bug Tracker" = "https://github.com/jonah-sullivan/plugin_build_tool/issues"

[project.scripts]
pb_tool = "pb_tool.pb_tool:cli"
pbt = "pb_tool.pb_tool:cli"

[tool.hatch.build.targets.wheel]
packages = ["pb_tool"]
artifacts = [
    "pb_tool/templates",
]

[tool.pytest.ini_options]
testpaths = ["test_pb_tool.py"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "W", "F", "I"]
